on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh to pull latest version
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ubuntu
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd guess_map
            git pull origin main --no-edit
            yarn install
            yarn knex migrate:latest
            pm2 restart 0
